export oldPATH="/c/Python39/Scripts:/c/Python39:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/c/WATCOM/BINNT:/c/WATCOM/BINW:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/PuTTY:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/LLVM/bin:/c/Users/Gena2018115rus/Desktop/mingw gcc 10/mingw64/bin:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64:/c/Program Files/Microsoft VS Code Insiders/bin:/c/OSPanel/modules/php/PHP_7.3-x64:/c/Program Files (x86)/dotnet:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/node:/c/ProgramData/chocolatey/bin:/c/Users/Gena2018115rus/AppData/Local/Microsoft/WindowsApps:/c/Users/Gena2018115rus/.dotnet/tools:/c/Users/Gena2018115rus/AppData/Roaming/npm:/c/Users/Gena2018115rus/AppData/Local/gitkraken/bin"
export newPATH="/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/PuTTY:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64:/c/Program Files/Microsoft VS Code Insiders/bin:/c/OSPanel/modules/php/PHP_7.3-x64:/c/Program Files (x86)/dotnet:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/node:/c/ProgramData/chocolatey/bin:/c/Users/Gena2018115rus/AppData/Local/Microsoft/WindowsApps:/c/Users/Gena2018115rus/.dotnet/tools:/c/Users/Gena2018115rus/AppData/Roaming/npm:/c/Users/Gena2018115rus/AppData/Local/gitkraken/bin:/usr/bin"
export PATH=$newPATH
cd eth-lib
g++ -shared -g -m64 -std=gnu++17 -pedantic -O0 -Wall -static -static-libstdc++ eth-lib.cpp -o eth-lib.dll
cd ..
export PATH=$oldPATH
./bl.bat
export PATH=$newPATH
g++ -static main.dll -o main.exe Project1.o

